### ISSUE TITLE
Import error while using Docker

### ISSUE THREAD

**Issue by sonukiller** [filaPro/oneformer3d#10]
When running the repo using docker, I am getting, ImportError: Failed to import custom modules from {'imports': ['oneformer3d']}. I also checked mmengine custom import from [here](https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module), but couldn't be resolved. Can you please help with this?

**Comment by filaPro** [comment]
Can you please share the command you are running and the full log? I think adding `PYTHONPATH=./` before `python test.py ...` should help.

**Comment by sonukiller** [comment]
Thanks, it is working!

**Comment by russellyq** [comment]
> Can you please share the command you are running and the full log? I think adding `PYTHONPATH=./` before `python test.py ...` should help.

Hi @filaPro ,

After adding "PYTHONPATH=./  python ....." when running the command, I still cannot run the code.

FYI, I set up my conda env locally with mmdet3d

**Comment by oneformer3d-contributor** [comment]
Can you please share the full log including error message?

Also what do you mean by `with mmdet3d`, is it just `pip install ... mmdet3d ...`?

**Comment by russellyq** [comment]
> Can you please share the full log including error message?
> 
> Also what do you mean by `with mmdet3d`, is it just `pip install ... mmdet3d ...`?

Hi @oneformer3d-contributor ,

Thanks for your quick action.

I solved it myself. It is related to my python env settings.

By the way, when training on S3DIS, I find that the cuda memory varies from time to time. Even when running with batch size 1, GPU runs out of memory. I run on RTX4090.

Any answer to this ?

Thanks

**Comment by oneformer3d-contributor** [comment]
There are some very large scenes on S3DIS and we don't use crops. You can try with 32Gb GPU or follow #11.

**Comment by russellyq** [comment]
> There are some very large scenes on S3DIS and we don't use crops. You can try with 32Gb GPU or follow #11.

Hi @oneformer3d-contributor,

Thank you. I have successfully ran the code on S3DIS after resolving all the related issues.

May I ask for any codes on how to only evaluate on validation set ?

**Comment by oneformer3d-contributor** [comment]
`python tools/test.py ...` commands in the `readme` are basically for the evaluation on validation set.

**Comment by chinagalaxy2002** [comment]
> > Can you please share the full log including error message?您能否分享包含错误消息的完整日志？
> > Also what do you mean by `with mmdet3d`, is it just `pip install ... mmdet3d ...`?另外`with mmdet3d`是什么意思，它只是`pip install ... mmdet3d ...`吗？
> 
> Hi @oneformer3d-contributor ,  你好 ，
> 
> Thanks for your quick action.感谢您的快速行动。
> 
> I solved it myself. It is related to my python env settings.我自己解决了。这和我的python环境设置有关。
> 
> By the way, when training on S3DIS, I find that the cuda memory varies from time to time. Even when running with batch size 1, GPU runs out of memory. I run on RTX4090.顺便说一下，在S3DIS上训练时，我发现cuda内存有时会发生变化。即使以批量大小 1 运行，GPU 也会耗尽内存。我在 RTX4090 上运行。
> 
> Any answer to this ?对此有什么答案吗？
> 
> Thanks  谢谢
Could you please tell me how to solve it?
------------------------------------------------------
Traceback (most recent call last):
  File "vis_demo/online_demo.py", line 140, in <module>
    main()
  File "vis_demo/online_demo.py", line 98, in main
    model = init_model(config=args.config, checkpoint=args.checkpoint, device=args.device)
  File "/home/zh/miniconda3/envs/ESAM/lib/python3.8/site-packages/mmdet3d/apis/inference.py", line 59, in init_model
    config = Config.fromfile(config)
  File "/home/zh/miniconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/config/config.py", line 478, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['oneformer3d']}, the current sys.path is: 
    /home/zh/ESAM-main/vis_demo
    /home/zh/miniconda3/envs/ESAM/lib/python38.zip
    /home/zh/miniconda3/envs/ESAM/lib/python3.8
    /home/zh/miniconda3/envs/ESAM/lib/python3.8/lib-dynload
    /home/zh/miniconda3/envs/ESAM/lib/python3.8/site-packages
    /home/zh/miniconda3/envs/ESAM/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg
    /home/zh/miniconda3/envs/ESAM/lib/python3.8/site-packages/pointops-1.0-py3.8-linux-x86_64.egg
    /home/zh/ESAM-main
    /home/zh/work_dirs/tmp
    /home/zh/miniconda3/envs/ESAM/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module
