### ISSUE TITLE
Good results in initial epochs

### ISSUE THREAD

**Issue by sonukiller** [filaPro/oneformer3d#12]
For the S3DIS, I observe that the MIOUS, AP@50 are very close to the final results in the initial epochs. But when I used the initial checkpoints for testing, the results are very bad! Do you know why it is showing good results for validation data but bad for test data?

**Comment by filaPro** [comment]
Hi @sonukiller ,

For S3DIS validation and test data is exactly the same. Did not you forget to run [fix_spconv_checkpoint.py](https://github.com/filaPro/oneformer3d/blob/main/tools/fix_spconv_checkpoint.py) script between validation and test stages?

**Comment by sonukiller** [comment]
Thanks for the help!
