### ISSUE TITLE
Confusion about `QueryClassificationCost`

### ISSUE THREAD

**Issue by RayYoh** [filaPro/oneformer3d#13]
Dear Authors,

Thanks for your great work.

When I read the code, I was confused about why `QueryClassificationCost` uses `scores` but not `cls_preds` in the decoder.
![image](https://github.com/filaPro/oneformer3d/assets/35106336/e0b3cabe-404e-4dac-a55e-07d8ab63cc5d)

Looking forward to your reply.

Best,
Ray

**Comment by filaPro** [comment]
Looks like we store `cls_preds` as `scores` [here](https://github.com/filaPro/oneformer3d/blob/main/oneformer3d/instance_criterion.py#L253).

**Comment by RayYoh** [comment]
> Looks like we store `cls_preds` as `scores` [here](https://github.com/filaPro/oneformer3d/blob/main/oneformer3d/instance_criterion.py#L253).

Okay, I was careless. I only read the Matcher part, not paying attention to the previous parts.
