### ISSUE TITLE
mmdetection3d version

### ISSUE THREAD

**Issue by kabouzeid** [filaPro/oneformer3d#18]
Thank you for your hard work and for sharing the Dockerfile. It is greatly appreciated!

Why is `mmdetection3d` locked to `v1.1.0`? Will the newer version `v1.4.0` also be compatible, or is there a specific requirement for the older version?

**Comment by filaPro** [comment]
I think, 1.4.0 should be ok, may be just with increasing versions of mmcv, mmengine, etc.
