### ISSUE TITLE
how to train on own dataset

### ISSUE THREAD

**Issue by wojiazaiyugang** [filaPro/oneformer3d#2]

**Comment by filaPro** [comment]
Hi @wojiazaiyugang ,

Basically you can inherit from our `ScanNetSegDataset_` with just loading annotations of your own dataset in the same format. The main problem here is to segment your data with superpoints before training following our code [here](https://github.com/filaPro/oneformer3d/blob/main/data/scannet/batch_load_scannet_data.py#L87).

Also we are going to support S3DIS and Structured3D datasets in this repo soon. These model can be trained without superpoint clustering.

**Comment by wojiazaiyugang** [comment]
got it， thanks
