### ISSUE TITLE
Bounding Box Detection

### ISSUE THREAD

**Issue by kabouzeid** [filaPro/oneformer3d#21]
How can I evaluate the scores for bounding box detection? (Table 1 in the paper) Thanks in advance!

**Comment by kabouzeid** [comment]
Thank you for the detailed instructions, I appreciate your effort! One more question: should instance masks be post-processed to prevent accidental outliers before applying bbox fitting? I ask because Mask3D uses DBSCAN to avoid outliers, but it seems that OneFormer3D works well without DBSCAN post-processing?

**Comment by filaPro** [comment]
No post-processing is needed. We use matrix-nms but it is not important, and can be even disabled in config.
