### ISSUE TITLE
About the bach size

### ISSUE THREAD

**Issue by RayYoh** [filaPro/oneformer3d#22]
Hi Danila Rukhovich,

Thanks for your work. Recently I am trying to use your open-sourced code for 3D instance segmentation.
But my question is not about the method or the code. It is have you ever tried to use different batch size? (You know, 4 seems too slow to train.)

**Comment by filaPro** [comment]
If you have enough gpu memory larger barch size should be even slightly better.

**Comment by RayYoh** [comment]
> If you have enough gpu memory larger barch size should be even slightly better.

I also modified the lr correspondingly. I am worried about the final performance. Let me try it.

**Comment by yxchng** [comment]
@RayYoh do you get better performance with large batch size? what batch size do you use and with what parameters?

**Comment by yxchng** [comment]
@filaPro do i have to modify other parameters when i increase batch size?

**Comment by oneformer3d-contributor** [comment]
Basically the idea same to `--auto-scale-lr` is good. However we made only a few (almost none) tries on gpu with more than 32gb. So I can't help you much here.

**Comment by RayYoh** [comment]
> @RayYoh do you get better performance with large batch size? what batch size do you use and with what parameters?

A little bit worse than the paper, b4 * 3.
