### ISSUE TITLE
S3DISOneFormer3D has 2 loss

### ISSUE THREAD

**Issue by mcmingchang** [filaPro/oneformer3d#23]
S3DISOneFormer3D has 2 loss

**Comment by filaPro** [comment]
so, what is your question about?)

**Comment by mcmingchang** [comment]
Does the default use the second loss?

**Comment by filaPro** [comment]
Yes, default config for S3DIS dataset includes model.criterion.sem_criterion for semantic segmentation and model.criterion.inst_criterion for instance segmentation.
