### ISSUE TITLE
Google Colab environment

### ISSUE THREAD

**Issue by zeejja** [filaPro/oneformer3d#61]
I am trying to set up the environment in Google Colab, but it is not working. Has anyone managed to do it successfully?

**Comment by zeejja** [comment]
> I believe the problem is with MinkowskiEngine installation?

yes the proble is with MinkowskiEngine and 
!mim install "mmcv>=2.0.0rc4,<2.1.0"
!mim install "mmdet>=3.0.0,<3.1.0"

**Comment by oneformer3d-contributor** [comment]
Can you share some tracebacks of errors?

**Comment by zeejja** [comment]
> Can you share some tracebacks of errors?

when i try to execute : ''!mim install "mmcv>=2.0.0rc4,<2.1.0"''  

this is the error : 

Looking in links: https://download.openmmlab.com/mmcv/dist/cu121/torch2.3.0/index.html
Collecting mmcv<2.1.0,>=2.0.0rc4
  Downloading mmcv-2.0.1.tar.gz (469 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.5/469.5 kB 7.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in /usr/local/lib/python3.10/dist-packages (from mmcv<2.1.0,>=2.0.0rc4) (2.4.0)
Requirement already satisfied: mmengine>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from mmcv<2.1.0,>=2.0.0rc4) (0.10.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from mmcv<2.1.0,>=2.0.0rc4) (1.25.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from mmcv<2.1.0,>=2.0.0rc4) (24.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from mmcv<2.1.0,>=2.0.0rc4) (9.4.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from mmcv<2.1.0,>=2.0.0rc4) (6.0.1)
Requirement already satisfied: yapf in /usr/local/lib/python3.10/dist-packages (from mmcv<2.1.0,>=2.0.0rc4) (0.40.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (3.7.1)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (13.4.2)
Requirement already satisfied: termcolor in /usr/local/lib/python3.10/dist-packages (from mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (2.4.0)
Requirement already satisfied: opencv-python>=3 in /usr/local/lib/python3.10/dist-packages (from mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (4.8.0.76)
Requirement already satisfied: importlib-metadata>=6.6.0 in /usr/local/lib/python3.10/dist-packages (from yapf->mmcv<2.1.0,>=2.0.0rc4) (7.1.0)
Requirement already satisfied: platformdirs>=3.5.1 in /usr/local/lib/python3.10/dist-packages (from yapf->mmcv<2.1.0,>=2.0.0rc4) (4.2.2)
Requirement already satisfied: tomli>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from yapf->mmcv<2.1.0,>=2.0.0rc4) (2.0.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=6.6.0->yapf->mmcv<2.1.0,>=2.0.0rc4) (3.19.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (4.53.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (2.8.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->mmengine>=0.3.0->mmcv<2.1.0,>=2.0.0rc4) (1.16.0)
Building wheels for collected packages: mmcv
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for mmcv (setup.py) ... error
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects

**Comment by oneformer3d-contributor** [comment]
>cu121/torch2.3.0/index.html

torch2.3 may be too good for this repo. and cuda12 also may need some fixes in MinkowskiEngine

**Comment by oneformer3d-contributor** [comment]
> I use docker, also failed with MinkowskiEngine.

Please also provide the full log of error.

**Comment by zeejja** [comment]
> > cu121/torch2.3.0/index.html
> 
> torch2.3 est peut-être trop bon pour ce dépôt. et cuda12 peuvent également avoir besoin de quelques correctifs dans MinkowskiEngine



> > cu121/torch2.3.0/index.html
> 
> torch2.3 est peut-être trop bon pour ce dépôt. et cuda12 peuvent également avoir besoin de quelques correctifs dans MinkowskiEngine

How can I fix it, please? I am forced to work with Google Colab Pro because I don't have a local machine.

**Comment by oneformer3d-contributor** [comment]
You can downgrade torch to the version in our Dockerfile. And if you can not downgrade cuda, please use this fix https://github.com/NVIDIA/MinkowskiEngine/pull/567.

**Comment by zeejja** [comment]
> You can downgrade torch to the version in our Dockerfile. And if you can not downgrade cuda, please use this fix [NVIDIA/MinkowskiEngine#567](https://github.com/NVIDIA/MinkowskiEngine/pull/567).

for google colab ?

**Comment by oneformer3d-contributor** [comment]
> for google colab ?

yes, i think, it may work. just replace commit id from the dockerfile to the commit from this pr
