### ISSUE TITLE
Killed while validating

### ISSUE THREAD

**Issue by trandangtrungduc** [filaPro/oneformer3d#7]
I tried reproducing your results, and there were no problems.
Therefore, I am trying to retrain the model with ScanNet. However, when it comes to the validation step, it is killed as below.

`12/26 13:58:27 - mmengine - INFO - Epoch(train)  [48][ 50/601]  lr: 9.1683e-05  eta: 2 days, 0:33:45  time: 0.6257  data_time: 0.2475  memory: 11143  grad_norm: 13.7663  loss: 3.3742  inst_loss: 3.3041  seg_loss: 0.0701
12/26 13:58:53 - mmengine - INFO - Epoch(train)  [48][100/601]  lr: 9.1683e-05  eta: 1 day, 21:04:32  time: 0.5360  data_time: 0.3090  memory: 11035  grad_norm: 12.7602  loss: 3.2733  inst_loss: 3.2091  seg_loss: 0.0642
12/26 13:59:16 - mmengine - INFO - Epoch(train)  [48][150/601]  lr: 9.1683e-05  eta: 1 day, 17:30:27  time: 0.4432  data_time: 0.2229  memory: 5097  grad_norm: 12.0678  loss: 3.1115  inst_loss: 3.0499  seg_loss: 0.0615
12/26 13:59:39 - mmengine - INFO - Epoch(train)  [48][200/601]  lr: 9.1683e-05  eta: 1 day, 16:12:49  time: 0.4686  data_time: 0.2475  memory: 6837  grad_norm: 14.9487  loss: 3.8859  inst_loss: 3.8133  seg_loss: 0.0726
12/26 14:00:01 - mmengine - INFO - Epoch(train)  [48][250/601]  lr: 9.1683e-05  eta: 1 day, 15:04:04  time: 0.4450  data_time: 0.2252  memory: 5671  grad_norm: 14.1963  loss: 3.6582  inst_loss: 3.5859  seg_loss: 0.0723
12/26 14:00:26 - mmengine - INFO - Epoch(train)  [48][300/601]  lr: 9.1683e-05  eta: 1 day, 14:59:32  time: 0.4984  data_time: 0.2772  memory: 6853  grad_norm: 14.2701  loss: 3.6490  inst_loss: 3.5778  seg_loss: 0.0712
12/26 14:00:52 - mmengine - INFO - Epoch(train)  [48][350/601]  lr: 9.1683e-05  eta: 1 day, 15:07:47  time: 0.5159  data_time: 0.2938  memory: 4083  grad_norm: 12.0829  loss: 3.3766  inst_loss: 3.3084  seg_loss: 0.0681
12/26 14:01:17 - mmengine - INFO - Epoch(train)  [48][400/601]  lr: 9.1683e-05  eta: 1 day, 15:10:25  time: 0.5100  data_time: 0.2860  memory: 6286  grad_norm: 14.5475  loss: 3.8494  inst_loss: 3.7724  seg_loss: 0.0771
12/26 14:01:42 - mmengine - INFO - Epoch(train)  [48][450/601]  lr: 9.1683e-05  eta: 1 day, 14:59:02  time: 0.4841  data_time: 0.2640  memory: 4830  grad_norm: 12.6186  loss: 3.7493  inst_loss: 3.6751  seg_loss: 0.0742
12/26 14:02:04 - mmengine - INFO - Epoch(train)  [48][500/601]  lr: 9.1683e-05  eta: 1 day, 14:35:58  time: 0.4543  data_time: 0.2330  memory: 6703  grad_norm: 11.7831  loss: 3.3239  inst_loss: 3.2640  seg_loss: 0.0599
12/26 14:02:27 - mmengine - INFO - Epoch(train)  [48][550/601]  lr: 9.1683e-05  eta: 1 day, 14:19:22  time: 0.4598  data_time: 0.2418  memory: 5487  grad_norm: 13.6781  loss: 3.5361  inst_loss: 3.4593  seg_loss: 0.0768
12/26 14:02:50 - mmengine - INFO - Epoch(train)  [48][600/601]  lr: 9.1683e-05  eta: 1 day, 13:58:54  time: 0.4429  data_time: 0.2239  memory: 5478  grad_norm: 11.5150  loss: 3.4321  inst_loss: 3.3619  seg_loss: 0.0702
12/26 14:02:50 - mmengine - INFO - Exp name: tab3d_scannet_20231226_135747
12/26 14:02:50 - mmengine - INFO - Saving checkpoint at 48 epochs
/home/vcl/anaconda3/envs/1former1/lib/python3.8/site-packages/mmdet3d/structures/points/base_points.py:136: UserWarning: point got color value beyond [0, 255]
  warnings.warn('point got color value beyond [0, 255]')
12/26 14:03:00 - mmengine - INFO - Epoch(val)  [48][ 50/312]    eta: 0:00:45  time: 0.1748  data_time: 0.0862  memory: 1305  
12/26 14:03:13 - mmengine - INFO - Epoch(val)  [48][100/312]    eta: 0:00:46  time: 0.2614  data_time: 0.1792  memory: 2096  
12/26 14:03:21 - mmengine - INFO - Epoch(val)  [48][150/312]    eta: 0:00:32  time: 0.1635  data_time: 0.0893  memory: 1881  
12/26 14:03:34 - mmengine - INFO - Epoch(val)  [48][200/312]    eta: 0:00:23  time: 0.2463  data_time: 0.1555  memory: 1738  
12/26 14:03:46 - mmengine - INFO - Epoch(val)  [48][250/312]    eta: 0:00:13  time: 0.2471  data_time: 0.1640  memory: 1741  
12/26 14:03:57 - mmengine - INFO - Epoch(val)  [48][300/312]    eta: 0:00:02  time: 0.2153  data_time: 0.1298  memory: 2228  
12/26 14:04:12 - mmengine - INFO - |        |   IoU   |   PQ   |   RQ   |  SQ   |
12/26 14:04:12 - mmengine - INFO - |all     | 0.7139 | 0.6690 | 0.7509 | 0.8873 |
12/26 14:04:12 - mmengine - INFO - |wall    | 0.7876 | 0.7706 | 0.9396 | 0.8201 |
12/26 14:04:12 - mmengine - INFO - |floor   | 0.9413 | 0.9429 | 0.9968 | 0.9459 |
12/26 14:04:12 - mmengine - INFO - |cabinet | 0.6139 | 0.5614 | 0.6517 | 0.8615 |
12/26 14:04:12 - mmengine - INFO - |bed     | 0.8033 | 0.7854 | 0.8590 | 0.9143 |
12/26 14:04:12 - mmengine - INFO - |chair   | 0.8977 | 0.8165 | 0.8833 | 0.9243 |
12/26 14:04:12 - mmengine - INFO - |sofa    | 0.8304 | 0.7542 | 0.8394 | 0.8986 |
12/26 14:04:12 - mmengine - INFO - |table   | 0.7523 | 0.7284 | 0.8006 | 0.9099 |
12/26 14:04:12 - mmengine - INFO - |door    | 0.6253 | 0.5441 | 0.6418 | 0.8478 |
12/26 14:04:12 - mmengine - INFO - |window  | 0.6604 | 0.5576 | 0.6566 | 0.8492 |
12/26 14:04:12 - mmengine - INFO - |ookshelf| 0.6679 | 0.4463 | 0.5381 | 0.8295 |
12/26 14:04:12 - mmengine - INFO - |picture | 0.3484 | 0.4744 | 0.5168 | 0.9180 |
12/26 14:04:12 - mmengine - INFO - |counter | 0.6450 | 0.5173 | 0.6552 | 0.7896 |
12/26 14:04:12 - mmengine - INFO - |desk    | 0.6645 | 0.6102 | 0.7279 | 0.8382 |
12/26 14:04:12 - mmengine - INFO - |curtain | 0.7761 | 0.6202 | 0.7119 | 0.8713 |
12/26 14:04:12 - mmengine - INFO - |igerator| 0.4806 | 0.5285 | 0.5747 | 0.9196 |
12/26 14:04:12 - mmengine - INFO - |curtrain| 0.7695 | 0.7152 | 0.7812 | 0.9154 |
12/26 14:04:12 - mmengine - INFO - |toilet  | 0.9403 | 0.9316 | 0.9744 | 0.9561 |
12/26 14:04:12 - mmengine - INFO - |sink    | 0.7209 | 0.6541 | 0.7475 | 0.8750 |
12/26 14:04:12 - mmengine - INFO - |bathtub | 0.8636 | 0.8183 | 0.8571 | 0.9546 |
12/26 14:04:12 - mmengine - INFO - |urniture| 0.4898 | 0.6027 | 0.6646 | 0.9068 |
12/26 14:04:12 - mmengine - INFO - |nlabeled| 0.0000 | 0.0000 | 0.0000 | 0.0000 |
12/26 14:04:12 - mmengine - INFO - True Positive: 
12/26 14:04:12 - mmengine - INFO - 288  |       311     |       246     |       67      |1185    |       81      |       277     |       336     |       174     |       53      |100     |       38      |       99      |       42      |       25      |       25      |57      |       74      |       27      |       323     |       0
False Positive: 
12/26 14:04:12 - mmengine - INFO - 20   |       1       |       137     |       8       |130     |       15      |       65      |       244     |       74      |       67      |65      |       26      |       46      |       9       |       5       |       11      |2       |       26      |       5       |       119     |       0
False Negative: 
12/26 14:04:12 - mmengine - INFO - 17   |       1       |       126     |       14      |183     |       16      |       73      |       131     |       108     |       24      |122     |       14      |       28      |       25      |       32      |       3       |1       |       24      |       4       |       207     |       0
/home/vcl/anaconda3/envs/1former1/lib/python3.8/site-packages/mmdet3d/evaluation/functional/seg_eval.py:39: RuntimeWarning: invalid value encountered in divide
  return np.diag(hist) / (hist.sum(1) + hist.sum(0) - np.diag(hist))
/home/vcl/anaconda3/envs/1former1/lib/python3.8/site-packages/mmdet3d/evaluation/functional/seg_eval.py:67: RuntimeWarning: invalid value encountered in divide
  return np.nanmean(np.diag(hist) / hist.sum(axis=1))
12/26 14:04:12 - mmengine - INFO - 
+---------+--------+--------+---------+--------+--------+--------+--------+--------+--------+-----------+---------+---------+--------+---------+--------------+----------------+--------+--------+---------+----------------+-----------+--------+--------+---------+
| classes | wall   | floor  | cabinet | bed    | chair  | sofa   | table  | door   | window | bookshelf | picture | counter | desk   | curtain | refrigerator | showercurtrain | toilet | sink   | bathtub | otherfurniture | unlabeled | miou   | acc    | acc_cls |
+---------+--------+--------+---------+--------+--------+--------+--------+--------+--------+-----------+---------+---------+--------+---------+--------------+----------------+--------+--------+---------+----------------+-----------+--------+--------+---------+
| results | 0.8504 | 0.9727 | 0.6725  | 0.8244 | 0.9212 | 0.8867 | 0.7494 | 0.6363 | 0.6539 | 0.7683    | 0.3292  | 0.7129  | 0.6803 | 0.7868  | 0.5092       | 0.8066         | 0.8871 | 0.7018 | 0.8624  | 0.5408         | nan       | 0.7376 | 0.9043 | 0.8267  |
+---------+--------+--------+---------+--------+--------+--------+--------+--------+--------+-----------+---------+---------+--------+---------+--------------+----------------+--------+--------+---------+----------------+-----------+--------+--------+---------+
Killed`

I realized that the problem comes from out of memory (RAM). I am using 1 A5000 GPU (24GB) to train, do you have any solution for this problem?

**Comment by filaPro** [comment]
Have you tried the comment about RAM in our readme?

**Comment by trandangtrungduc** [comment]
> Have you tried the comment about RAM in our readme?
Yes, I tried. What is the minimum amount of RAM you have?

**Comment by filaPro** [comment]
I've never tried it on a machine with less then 60 Gb RAM. Basically it is an issue of ScanNet instance segmentation evaluator :( I recommend to decrease `model.test_cfg.topk_insts` from 600 to 200 and increase `model.test_cfg.inst_score_thr` from 0.0 to 0.05. It will have negligible effect on overall metrics, e.g. < 1% mAP. You can return these values back after training or on another machine to achieve this last 1% of mAP.
