### ISSUE TITLE
ScanNet dataset

### ISSUE THREAD

**Issue by D1st3f** [filaPro/oneformer3d#76]
Is really need to download all 1.3Tb dataset, or I can use some individual scenes?

**Comment by filaPro** [comment]
99% of this data is rgb and depth image, and you need only 1 point cloud per scene. Btw you can try downloading ScanNet data from [here](https://huggingface.co/datasets/maksimko123/UniDet3D/tree/main).

**Comment by D1st3f** [comment]
ok, i downloaded this dataset, unzip, but 

All scenes skiped
scene0706_00
Failed export scan: scene0706_00
--------------------done

Stucture of dataset:
<img width="463" alt="Знімок екрана 2024-09-19 о 21 38 08" src="https://github.com/user-attachments/assets/1e4b73b9-d42c-4e7e-bb9c-15dbb2ab0b4b">


But for python batch_load_scannet_data.py needs "scans" folder, can you help pls?

**Comment by filaPro** [comment]
These are already preprocessed files. And hopefully they are the same for unidet3d and oneformer3d.
