### ISSUE TITLE
Why No Center Shift during Data Augmentation ?

### ISSUE THREAD

**Issue by accoumar12** [filaPro/oneformer3d#86]
Hello,
Again thank you for your work. I took your baseline and notably incorporate the normals replacing the colors for my use case and the results are really good.
I was wondering why you did not perform a center shift during data augmentation, in order to have data centered at the origin.
This is a common practise that I saw for example in the Pointcept models.

**Comment by filaPro** [comment]
As we don't use coordinate features, and other features are invariant to shifts. However we apply small shifts [here](https://github.com/filaPro/oneformer3d/blob/main/configs/oneformer3d_1xb4_scannet.py#L110) just to augment voxelization.

**Comment by accoumar12** [comment]
> As we don't use coordinate features, and other features are invariant to shifts. However we apply small shifts [here](https://github.com/filaPro/oneformer3d/blob/main/configs/oneformer3d_1xb4_scannet.py#L110) just to augment voxelization.

Maybe it is a silly question, but isn't the input of the 3D u net point coordinates (and colors) ?
Thanks for your help !

**Comment by filaPro** [comment]
Ah yes, sorry, it is true. As we borrowed spconv unet from spformer, we use 6 input channels. But it is not so important. For example for scannet200 with use minkowski unet with just [3 input channels](https://github.com/filaPro/oneformer3d/blob/main/configs/oneformer3d_1xb4_scannet200.py#L19).

**Comment by accoumar12** [comment]
Ok. I still believe center shifting is important since we use coordinates as input to the model. I will come back to you if I find major benefits to using it.

**Comment by accoumar12** [comment]
FYI, Center Shifting indeed does not bring any value to the training.
