### ISSUE TITLE
when i run train.py,it just stoped

### ISSUE THREAD

**Issue by shaonianG** [filaPro/oneformer3d#88]
i run your dockerfile,and pytorch is 1.13.1,cuda is 11.6,python is 3.10
then i run `python tools/train.py configs/oneformer3d_1xb2_s3dis-area-5.py` to trian
log is in following,it just stop in 
`/opt/conda/lib/python3.10/site-packages/mmdet3d/structures/points/base_points.py:136: UserWarning: point got color value beyond [0, 255]
  warnings.warn('point got color value beyond [0, 255]'`

and didn't show any thing,do you know anying wrong about this status?may be i should run it longer?

`root@f86cf77eb62f:/workspace# python tools/train.py configs/oneformer3d_1xb2_s3dis-area-5.py
['/workspace/tools', '/workspace', '/opt/conda/lib/python310.zip', '/opt/conda/lib/python3.10', '/opt/conda/lib/python3.10/lib-dynload', '/opt/conda/lib/python3.10/site-packages', '/opt/conda/lib/python3.10/site-packages/PyYAML-6.0-py3.10-linux-x86_64.egg', '/tmp/tmph_u4seb7', '/workspace/oneformer3d']
/opt/conda/lib/python3.10/site-packages/mmdet3d/evaluation/functional/kitti_utils/eval.py:10: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def get_thresholds(scores: np.ndarray, num_gt, num_sample_pts=41):
11/01 10:56:32 - mmengine - INFO -
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.10.8 (main, Nov  4 2022, 13:48:29) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 1896054153
    GPU 0: NVIDIA GeForce RTX 4070 SUPER
    CUDA_HOME: /opt/conda
    NVCC: Cuda compilation tools, release 11.6, V11.6.124
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 1.13.1
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

    TorchVision: 0.14.1
    OpenCV: 4.7.0
    MMEngine: 0.7.3

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

11/01 10:56:33 - mmengine - INFO - Config:
default_scope = 'mmdet3d'
default_hooks = dict(
    timer=dict(type='IterTimerHook', _scope_='mmdet3d'),
    logger=dict(type='LoggerHook', interval=50, _scope_='mmdet3d'),
    param_scheduler=dict(type='ParamSchedulerHook', _scope_='mmdet3d'),
    checkpoint=dict(
        type='CheckpointHook',
        interval=16,
        _scope_='mmdet3d',
        max_keep_ckpts=1,
        save_best=['all_ap_50%', 'miou'],
        rule='greater'),
    sampler_seed=dict(type='DistSamplerSeedHook', _scope_='mmdet3d'),
    visualization=dict(type='Det3DVisualizationHook', _scope_='mmdet3d'))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
log_processor = dict(
    type='LogProcessor', window_size=50, by_epoch=True, _scope_='mmdet3d')
log_level = 'INFO'
load_from = 'work_dirs/tmp/instance-only-oneformer3d_1xb2_scannet-and-structured3d.pth'
resume = False
custom_imports = dict(imports=['oneformer3d'])
num_channels = 64
num_instance_classes = 13
num_semantic_classes = 13
model = dict(
    type='S3DISOneFormer3D',
    data_preprocessor=dict(type='Det3DDataPreprocessor'),
    in_channels=6,
    num_channels=64,
    voxel_size=0.05,
    num_classes=13,
    min_spatial_shape=128,
    backbone=dict(
        type='SpConvUNet',
        num_planes=[64, 128, 192, 256, 320],
        return_blocks=True),
    decoder=dict(
        type='QueryDecoder',
        num_layers=3,
        num_classes=13,
        num_instance_queries=400,
        num_semantic_queries=13,
        num_instance_classes=13,
        in_channels=64,
        d_model=256,
        num_heads=8,
        hidden_dim=1024,
        dropout=0.0,
        activation_fn='gelu',
        iter_pred=True,
        attn_mask=True,
        fix_attention=True,
        objectness_flag=True),
    criterion=dict(
        type='S3DISUnifiedCriterion',
        num_semantic_classes=13,
        sem_criterion=dict(type='S3DISSemanticCriterion', loss_weight=5.0),
        inst_criterion=dict(
            type='InstanceCriterion',
            matcher=dict(
                type='HungarianMatcher',
                costs=[
                    dict(type='QueryClassificationCost', weight=0.5),
                    dict(type='MaskBCECost', weight=1.0),
                    dict(type='MaskDiceCost', weight=1.0)
                ]),
            loss_weight=[0.5, 1.0, 1.0, 0.5],
            num_classes=13,
            non_object_weight=0.05,
            fix_dice_loss_weight=True,
            iter_matcher=True,
            fix_mean_loss=True)),
    train_cfg=dict(),
    test_cfg=dict(
        topk_insts=450,
        inst_score_thr=0.0,
        pan_score_thr=0.4,
        npoint_thr=300,
        obj_normalization=True,
        obj_normalization_thr=0.01,
        sp_score_thr=0.15,
        nms=True,
        matrix_nms_kernel='linear',
        num_sem_cls=13,
        stuff_cls=[0, 1, 2, 3, 4, 5, 6, 12],
        thing_cls=[7, 8, 9, 10, 11]))
dataset_type = 'S3DISSegDataset_'
data_root = 'data/s3dis/'
data_prefix = dict(
    pts='points',
    pts_instance_mask='instance_mask',
    pts_semantic_mask='semantic_mask')
train_area = [1, 2, 3, 4, 6]
test_area = 5
train_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='DEPTH',
        shift_height=False,
        use_color=True,
        load_dim=6,
        use_dim=[0, 1, 2, 3, 4, 5]),
    dict(
        type='LoadAnnotations3D',
        with_label_3d=False,
        with_bbox_3d=False,
        with_mask_3d=True,
        with_seg_3d=True),
    dict(type='PointSample_', num_points=180000),
    dict(type='PointInstClassMapping_', num_classes=13),
    dict(
        type='RandomFlip3D',
        sync_2d=False,
        flip_ratio_bev_horizontal=0.5,
        flip_ratio_bev_vertical=0.5),
    dict(
        type='GlobalRotScaleTrans',
        rot_range=[0.0, 0.0],
        scale_ratio_range=[0.9, 1.1],
        translation_std=[0.1, 0.1, 0.1],
        shift_height=False),
    dict(type='NormalizePointsColor_', color_mean=[127.5, 127.5, 127.5]),
    dict(
        type='Pack3DDetInputs_',
        keys=[
            'points', 'gt_labels_3d', 'pts_semantic_mask', 'pts_instance_mask'
        ])
]
test_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='DEPTH',
        shift_height=False,
        use_color=True,
        load_dim=6,
        use_dim=[0, 1, 2, 3, 4, 5]),
    dict(
        type='LoadAnnotations3D',
        with_bbox_3d=False,
        with_label_3d=False,
        with_mask_3d=True,
        with_seg_3d=True),
    dict(
        type='MultiScaleFlipAug3D',
        img_scale=(1333, 800),
        pts_scale_ratio=1,
        flip=False,
        transforms=[
            dict(
                type='NormalizePointsColor_', color_mean=[127.5, 127.5, 127.5])
        ]),
    dict(type='Pack3DDetInputs_', keys=['points'])
]
train_dataloader = dict(
    batch_size=2,
    num_workers=3,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='ConcatDataset',
        datasets=[
            dict(
                type='S3DISSegDataset_',
                data_root='data/s3dis/',
                ann_file='s3dis_infos_Area_1.pkl',
                pipeline=[
                    dict(
                        type='LoadPointsFromFile',
                        coord_type='DEPTH',
                        shift_height=False,
                        use_color=True,
                        load_dim=6,
                        use_dim=[0, 1, 2, 3, 4, 5]),
                    dict(
                        type='LoadAnnotations3D',
                        with_label_3d=False,
                        with_bbox_3d=False,
                        with_mask_3d=True,
                        with_seg_3d=True),
                    dict(type='PointSample_', num_points=180000),
                    dict(type='PointInstClassMapping_', num_classes=13),
                    dict(
                        type='RandomFlip3D',
                        sync_2d=False,
                        flip_ratio_bev_horizontal=0.5,
                        flip_ratio_bev_vertical=0.5),
                    dict(
                        type='GlobalRotScaleTrans',
                        rot_range=[0.0, 0.0],
                        scale_ratio_range=[0.9, 1.1],
                        translation_std=[0.1, 0.1, 0.1],
                        shift_height=False),
                    dict(
                        type='NormalizePointsColor_',
                        color_mean=[127.5, 127.5, 127.5]),
                    dict(
                        type='Pack3DDetInputs_',
                        keys=[
                            'points', 'gt_labels_3d', 'pts_semantic_mask',
                            'pts_instance_mask'
                        ])
                ],
                filter_empty_gt=True,
                data_prefix=dict(
                    pts='points',
                    pts_instance_mask='instance_mask',
                    pts_semantic_mask='semantic_mask'),
                box_type_3d='Depth',
                backend_args=None),
            dict(
                type='S3DISSegDataset_',
                data_root='data/s3dis/',
                ann_file='s3dis_infos_Area_2.pkl',
                pipeline=[
                    dict(
                        type='LoadPointsFromFile',
                        coord_type='DEPTH',
                        shift_height=False,
                        use_color=True,
                        load_dim=6,
                        use_dim=[0, 1, 2, 3, 4, 5]),
                    dict(
                        type='LoadAnnotations3D',
                        with_label_3d=False,
                        with_bbox_3d=False,
                        with_mask_3d=True,
                        with_seg_3d=True),
                    dict(type='PointSample_', num_points=180000),
                    dict(type='PointInstClassMapping_', num_classes=13),
                    dict(
                        type='RandomFlip3D',
                        sync_2d=False,
                        flip_ratio_bev_horizontal=0.5,
                        flip_ratio_bev_vertical=0.5),
                    dict(
                        type='GlobalRotScaleTrans',
                        rot_range=[0.0, 0.0],
                        scale_ratio_range=[0.9, 1.1],
                        translation_std=[0.1, 0.1, 0.1],
                        shift_height=False),
                    dict(
                        type='NormalizePointsColor_',
                        color_mean=[127.5, 127.5, 127.5]),
                    dict(
                        type='Pack3DDetInputs_',
                        keys=[
                            'points', 'gt_labels_3d', 'pts_semantic_mask',
                            'pts_instance_mask'
                        ])
                ],
                filter_empty_gt=True,
                data_prefix=dict(
                    pts='points',
                    pts_instance_mask='instance_mask',
                    pts_semantic_mask='semantic_mask'),
                box_type_3d='Depth',
                backend_args=None),
            dict(
                type='S3DISSegDataset_',
                data_root='data/s3dis/',
                ann_file='s3dis_infos_Area_3.pkl',
                pipeline=[
                    dict(
                        type='LoadPointsFromFile',
                        coord_type='DEPTH',
                        shift_height=False,
                        use_color=True,
                        load_dim=6,
                        use_dim=[0, 1, 2, 3, 4, 5]),
                    dict(
                        type='LoadAnnotations3D',
                        with_label_3d=False,
                        with_bbox_3d=False,
                        with_mask_3d=True,
                        with_seg_3d=True),
                    dict(type='PointSample_', num_points=180000),
                    dict(type='PointInstClassMapping_', num_classes=13),
                    dict(
                        type='RandomFlip3D',
                        sync_2d=False,
                        flip_ratio_bev_horizontal=0.5,
                        flip_ratio_bev_vertical=0.5),
                    dict(
                        type='GlobalRotScaleTrans',
                        rot_range=[0.0, 0.0],
                        scale_ratio_range=[0.9, 1.1],
                        translation_std=[0.1, 0.1, 0.1],
                        shift_height=False),
                    dict(
                        type='NormalizePointsColor_',
                        color_mean=[127.5, 127.5, 127.5]),
                    dict(
                        type='Pack3DDetInputs_',
                        keys=[
                            'points', 'gt_labels_3d', 'pts_semantic_mask',
                            'pts_instance_mask'
                        ])
                ],
                filter_empty_gt=True,
                data_prefix=dict(
                    pts='points',
                    pts_instance_mask='instance_mask',
                    pts_semantic_mask='semantic_mask'),
                box_type_3d='Depth',
                backend_args=None),
            dict(
                type='S3DISSegDataset_',
                data_root='data/s3dis/',
                ann_file='s3dis_infos_Area_4.pkl',
                pipeline=[
                    dict(
                        type='LoadPointsFromFile',
                        coord_type='DEPTH',
                        shift_height=False,
                        use_color=True,
                        load_dim=6,
                        use_dim=[0, 1, 2, 3, 4, 5]),
                    dict(
                        type='LoadAnnotations3D',
                        with_label_3d=False,
                        with_bbox_3d=False,
                        with_mask_3d=True,
                        with_seg_3d=True),
                    dict(type='PointSample_', num_points=180000),
                    dict(type='PointInstClassMapping_', num_classes=13),
                    dict(
                        type='RandomFlip3D',
                        sync_2d=False,
                        flip_ratio_bev_horizontal=0.5,
                        flip_ratio_bev_vertical=0.5),
                    dict(
                        type='GlobalRotScaleTrans',
                        rot_range=[0.0, 0.0],
                        scale_ratio_range=[0.9, 1.1],
                        translation_std=[0.1, 0.1, 0.1],
                        shift_height=False),
                    dict(
                        type='NormalizePointsColor_',
                        color_mean=[127.5, 127.5, 127.5]),
                    dict(
                        type='Pack3DDetInputs_',
                        keys=[
                            'points', 'gt_labels_3d', 'pts_semantic_mask',
                            'pts_instance_mask'
                        ])
                ],
                filter_empty_gt=True,
                data_prefix=dict(
                    pts='points',
                    pts_instance_mask='instance_mask',
                    pts_semantic_mask='semantic_mask'),
                box_type_3d='Depth',
                backend_args=None),
            dict(
                type='S3DISSegDataset_',
                data_root='data/s3dis/',
                ann_file='s3dis_infos_Area_6.pkl',
                pipeline=[
                    dict(
                        type='LoadPointsFromFile',
                        coord_type='DEPTH',
                        shift_height=False,
                        use_color=True,
                        load_dim=6,
                        use_dim=[0, 1, 2, 3, 4, 5]),
                    dict(
                        type='LoadAnnotations3D',
                        with_label_3d=False,
                        with_bbox_3d=False,
                        with_mask_3d=True,
                        with_seg_3d=True),
                    dict(type='PointSample_', num_points=180000),
                    dict(type='PointInstClassMapping_', num_classes=13),
                    dict(
                        type='RandomFlip3D',
                        sync_2d=False,
                        flip_ratio_bev_horizontal=0.5,
                        flip_ratio_bev_vertical=0.5),
                    dict(
                        type='GlobalRotScaleTrans',
                        rot_range=[0.0, 0.0],
                        scale_ratio_range=[0.9, 1.1],
                        translation_std=[0.1, 0.1, 0.1],
                        shift_height=False),
                    dict(
                        type='NormalizePointsColor_',
                        color_mean=[127.5, 127.5, 127.5]),
                    dict(
                        type='Pack3DDetInputs_',
                        keys=[
                            'points', 'gt_labels_3d', 'pts_semantic_mask',
                            'pts_instance_mask'
                        ])
                ],
                filter_empty_gt=True,
                data_prefix=dict(
                    pts='points',
                    pts_instance_mask='instance_mask',
                    pts_semantic_mask='semantic_mask'),
                box_type_3d='Depth',
                backend_args=None)
        ]))
val_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='S3DISSegDataset_',
        data_root='data/s3dis/',
        ann_file='s3dis_infos_Area_5.pkl',
        pipeline=[
            dict(
                type='LoadPointsFromFile',
                coord_type='DEPTH',
                shift_height=False,
                use_color=True,
                load_dim=6,
                use_dim=[0, 1, 2, 3, 4, 5]),
            dict(
                type='LoadAnnotations3D',
                with_bbox_3d=False,
                with_label_3d=False,
                with_mask_3d=True,
                with_seg_3d=True),
            dict(
                type='MultiScaleFlipAug3D',
                img_scale=(1333, 800),
                pts_scale_ratio=1,
                flip=False,
                transforms=[
                    dict(
                        type='NormalizePointsColor_',
                        color_mean=[127.5, 127.5, 127.5])
                ]),
            dict(type='Pack3DDetInputs_', keys=['points'])
        ],
        test_mode=True,
        data_prefix=dict(
            pts='points',
            pts_instance_mask='instance_mask',
            pts_semantic_mask='semantic_mask'),
        box_type_3d='Depth',
        backend_args=None))
test_dataloader = dict(
    batch_size=1,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='S3DISSegDataset_',
        data_root='data/s3dis/',
        ann_file='s3dis_infos_Area_5.pkl',
        pipeline=[
            dict(
                type='LoadPointsFromFile',
                coord_type='DEPTH',
                shift_height=False,
                use_color=True,
                load_dim=6,
                use_dim=[0, 1, 2, 3, 4, 5]),
            dict(
                type='LoadAnnotations3D',
                with_bbox_3d=False,
                with_label_3d=False,
                with_mask_3d=True,
                with_seg_3d=True),
            dict(
                type='MultiScaleFlipAug3D',
                img_scale=(1333, 800),
                pts_scale_ratio=1,
                flip=False,
                transforms=[
                    dict(
                        type='NormalizePointsColor_',
                        color_mean=[127.5, 127.5, 127.5])
                ]),
            dict(type='Pack3DDetInputs_', keys=['points'])
        ],
        test_mode=True,
        data_prefix=dict(
            pts='points',
            pts_instance_mask='instance_mask',
            pts_semantic_mask='semantic_mask'),
        box_type_3d='Depth',
        backend_args=None))
class_names = [
    'ceiling', 'floor', 'wall', 'beam', 'column', 'window', 'door', 'table',
    'chair', 'sofa', 'bookcase', 'board', 'clutter', 'unlabeled'
]
label2cat = dict({
    0: 'ceiling',
    1: 'floor',
    2: 'wall',
    3: 'beam',
    4: 'column',
    5: 'window',
    6: 'door',
    7: 'table',
    8: 'chair',
    9: 'sofa',
    10: 'bookcase',
    11: 'board',
    12: 'clutter',
    13: 'unlabeled'
})
metric_meta = dict(
    label2cat=dict({
        0: 'ceiling',
        1: 'floor',
        2: 'wall',
        3: 'beam',
        4: 'column',
        5: 'window',
        6: 'door',
        7: 'table',
        8: 'chair',
        9: 'sofa',
        10: 'bookcase',
        11: 'board',
        12: 'clutter',
        13: 'unlabeled'
    }),
    ignore_index=[13],
    classes=[
        'ceiling', 'floor', 'wall', 'beam', 'column', 'window', 'door',
        'table', 'chair', 'sofa', 'bookcase', 'board', 'clutter', 'unlabeled'
    ],
    dataset_name='S3DIS')
sem_mapping = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
val_evaluator = dict(
    type='UnifiedSegMetric',
    stuff_class_inds=[0, 1, 2, 3, 4, 5, 6, 12],
    thing_class_inds=[7, 8, 9, 10, 11],
    min_num_points=1,
    id_offset=65536,
    sem_mapping=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    inst_mapping=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    submission_prefix_semantic=None,
    submission_prefix_instance=None,
    metric_meta=dict(
        label2cat=dict({
            0: 'ceiling',
            1: 'floor',
            2: 'wall',
            3: 'beam',
            4: 'column',
            5: 'window',
            6: 'door',
            7: 'table',
            8: 'chair',
            9: 'sofa',
            10: 'bookcase',
            11: 'board',
            12: 'clutter',
            13: 'unlabeled'
        }),
        ignore_index=[13],
        classes=[
            'ceiling', 'floor', 'wall', 'beam', 'column', 'window', 'door',
            'table', 'chair', 'sofa', 'bookcase', 'board', 'clutter',
            'unlabeled'
        ],
        dataset_name='S3DIS'))
test_evaluator = dict(
    type='UnifiedSegMetric',
    stuff_class_inds=[0, 1, 2, 3, 4, 5, 6, 12],
    thing_class_inds=[7, 8, 9, 10, 11],
    min_num_points=1,
    id_offset=65536,
    sem_mapping=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    inst_mapping=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    submission_prefix_semantic=None,
    submission_prefix_instance=None,
    metric_meta=dict(
        label2cat=dict({
            0: 'ceiling',
            1: 'floor',
            2: 'wall',
            3: 'beam',
            4: 'column',
            5: 'window',
            6: 'door',
            7: 'table',
            8: 'chair',
            9: 'sofa',
            10: 'bookcase',
            11: 'board',
            12: 'clutter',
            13: 'unlabeled'
        }),
        ignore_index=[13],
        classes=[
            'ceiling', 'floor', 'wall', 'beam', 'column', 'window', 'door',
            'table', 'chair', 'sofa', 'bookcase', 'board', 'clutter',
            'unlabeled'
        ],
        dataset_name='S3DIS'))
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=0.0001, weight_decay=0.05),
    clip_grad=dict(max_norm=10, norm_type=2))
param_scheduler = dict(type='PolyLR', begin=0, end=512, power=0.9)
custom_hooks = [dict(type='EmptyCacheHook', after_iter=True)]
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=512, val_interval=16)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
launcher = 'none'
work_dir = './work_dirs/oneformer3d_1xb2_s3dis-area-5'

11/01 10:56:36 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
11/01 10:56:36 - mmengine - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) RuntimeInfoHook
(BELOW_NORMAL) LoggerHook
 --------------------
before_train:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(VERY_LOW    ) CheckpointHook
 --------------------
before_train_epoch:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(NORMAL      ) DistSamplerSeedHook
(NORMAL      ) EmptyCacheHook
 --------------------
before_train_iter:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
 --------------------
after_train_iter:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(NORMAL      ) EmptyCacheHook
(BELOW_NORMAL) LoggerHook
(LOW         ) ParamSchedulerHook
(VERY_LOW    ) CheckpointHook
 --------------------
after_train_epoch:
(NORMAL      ) IterTimerHook
(NORMAL      ) EmptyCacheHook
(LOW         ) ParamSchedulerHook
(VERY_LOW    ) CheckpointHook
 --------------------
before_val_epoch:
(NORMAL      ) IterTimerHook
(NORMAL      ) EmptyCacheHook
 --------------------
before_val_iter:
(NORMAL      ) IterTimerHook
 --------------------
after_val_iter:
(NORMAL      ) IterTimerHook
(NORMAL      ) Det3DVisualizationHook
(NORMAL      ) EmptyCacheHook
(BELOW_NORMAL) LoggerHook
 --------------------
after_val_epoch:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(NORMAL      ) EmptyCacheHook
(BELOW_NORMAL) LoggerHook
(LOW         ) ParamSchedulerHook
(VERY_LOW    ) CheckpointHook
 --------------------
after_train:
(VERY_LOW    ) CheckpointHook
 --------------------
before_test_epoch:
(NORMAL      ) IterTimerHook
(NORMAL      ) EmptyCacheHook
 --------------------
before_test_iter:
(NORMAL      ) IterTimerHook
 --------------------
after_test_iter:
(NORMAL      ) IterTimerHook
(NORMAL      ) Det3DVisualizationHook
(NORMAL      ) EmptyCacheHook
(BELOW_NORMAL) LoggerHook
 --------------------
after_test_epoch:
(VERY_HIGH   ) RuntimeInfoHook
(NORMAL      ) IterTimerHook
(NORMAL      ) EmptyCacheHook
(BELOW_NORMAL) LoggerHook
 --------------------
after_run:
(BELOW_NORMAL) LoggerHook
 --------------------
11/01 10:56:37 - mmengine - INFO - ------------------------------
11/01 10:56:37 - mmengine - INFO - The length of the dataset: 44
11/01 10:56:37 - mmengine - INFO - The number of instances per category in the dataset:
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 69     |
| floor    | 155    |
| wall     | 6      |
| beam     | 90     |
| column   | 27     |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
11/01 10:56:37 - mmengine - INFO - ------------------------------
11/01 10:56:37 - mmengine - INFO - The length of the dataset: 40
11/01 10:56:37 - mmengine - INFO - The number of instances per category in the dataset:
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 46     |
| floor    | 545    |
| wall     | 6      |
| beam     | 47     |
| column   | 17     |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
11/01 10:56:37 - mmengine - INFO - ------------------------------
11/01 10:56:37 - mmengine - INFO - The length of the dataset: 23
11/01 10:56:37 - mmengine - INFO - The number of instances per category in the dataset:
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 30     |
| floor    | 67     |
| wall     | 9      |
| beam     | 41     |
| column   | 12     |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
11/01 10:56:37 - mmengine - INFO - ------------------------------
11/01 10:56:37 - mmengine - INFO - The length of the dataset: 49
11/01 10:56:37 - mmengine - INFO - The number of instances per category in the dataset:
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 79     |
| floor    | 159    |
| wall     | 14     |
| beam     | 98     |
| column   | 10     |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
11/01 10:56:37 - mmengine - INFO - ------------------------------
11/01 10:56:37 - mmengine - INFO - The length of the dataset: 48
11/01 10:56:37 - mmengine - INFO - The number of instances per category in the dataset:
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 77     |
| floor    | 179    |
| wall     | 9      |
| beam     | 90     |
| column   | 29     |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
11/01 10:56:38 - mmengine - INFO - ------------------------------
11/01 10:56:38 - mmengine - INFO - The length of the dataset: 68
11/01 10:56:38 - mmengine - INFO - The number of instances per category in the dataset:
+----------+--------+
| category | number |
+----------+--------+
| ceiling  | 154    |
| floor    | 258    |
| wall     | 11     |
| beam     | 217    |
| column   | 42     |
| window   | 0      |
| door     | 0      |
| table    | 0      |
| chair    | 0      |
| sofa     | 0      |
| bookcase | 0      |
| board    | 0      |
| clutter  | 0      |
+----------+--------+
11/01 10:56:38 - mmengine - WARNING - The prefix is not set in metric class UnifiedSegMetric.
Loads checkpoint by local backend from path: work_dirs/tmp/instance-only-oneformer3d_1xb2_scannet-and-structured3d.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: decoder.queries_1dataset.weight, decoder.queries_2dataset.weight, decoder.out_cls_1dataset.0.weight, decoder.out_cls_1dataset.0.bias, decoder.out_cls_1dataset.2.weight, decoder.out_cls_1dataset.2.bias, decoder.out_cls_2dataset.0.weight, decoder.out_cls_2dataset.0.bias, decoder.out_cls_2dataset.2.weight, decoder.out_cls_2dataset.2.bias

missing keys in source state_dict: decoder.query.weight, decoder.out_cls.0.weight, decoder.out_cls.0.bias, decoder.out_cls.2.weight, decoder.out_cls.2.bias

11/01 10:56:40 - mmengine - INFO - Load checkpoint from work_dirs/tmp/instance-only-oneformer3d_1xb2_scannet-and-structured3d.pth
11/01 10:56:40 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
11/01 10:56:40 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
11/01 10:56:40 - mmengine - INFO - Checkpoints will be saved to /workspace/work_dirs/oneformer3d_1xb2_s3dis-area-5.
/opt/conda/lib/python3.10/site-packages/mmdet3d/structures/points/base_points.py:136: UserWarning: point got color value beyond [0, 255]
  warnings.warn('point got color value beyond [0, 255]')
/opt/conda/lib/python3.10/site-packages/mmdet3d/structures/points/base_points.py:136: UserWarning: point got color value beyond [0, 255]
  warnings.warn('point got color value beyond [0, 255]')
/opt/conda/lib/python3.10/site-packages/mmdet3d/structures/points/base_points.py:136: UserWarning: point got color value beyond [0, 255]
  warnings.warn('point got color value beyond [0, 255]')`

my gpu is full,so it's training?
<img width="207" alt="截屏2024-11-01 下午6 49 38" src="https://github.com/user-attachments/assets/8a0a30db-4ac4-4bba-8c2e-9da4973fcdb4">

**Comment by filaPro** [comment]
Hard to say something( If it is training there should be a log message approximately once a minute. You can check our log as an example.
