### ISSUE TITLE
How to use OneFormer3D for 3D object detection using segmentation results?

### ISSUE THREAD

**Issue by Treakun** [filaPro/oneformer3d#90]
I am trying to use OneFormer3D for 3D object detection by generating axis-aligned bounding boxes based on segmentation results, as mentioned in the paper. However, I couldn't find relevant code in the repository. Could you guide me on how to implement this?

**Comment by filaPro** [comment]
Please follow #21.

**Comment by Treakun** [comment]
Thank you for your guidance!
