### ISSUE TITLE
About the results of panoptic segmentation

### ISSUE THREAD

**Issue by jeff2048** [filaPro/oneformer3d#92]
Dear Authors,

I am truly inspired by your excellent work and am currently working on reproducing the results. I noticed that the provided code only includes the overall PQ results. Could you kindly guide me on **how to obtain the PQth and PQst results** as well?
Thank you in advance for your time and assistance!

**Comment by filaPro** [comment]
i think, you can just average PQ scores for semantic classes (wall, floor) to get PQ_st, and instance classes (other 18) to get PQ_th

**Comment by jeff2048** [comment]
> i think, you can just average PQ scores for semantic classes (wall, floor) to get PQ_st, and instance classes (other 18) to get PQ_th

Thank you for your response. It seems that the codes just provide the overall results of PQ.(https://github.com/filaPro/oneformer3d/blob/e2a9dd2656d4b2806853c026cab7bc63201f8814/oneformer3d/unified_metric.py#L137)

Could you please help me how to get the results of each class separately?

**Comment by filaPro** [comment]
you can have a look at out log file. it contains per class metrics. so, this ret_pan dict should contain per class metrics

**Comment by jeff2048** [comment]
> you can have a look at out log file. it contains per class metrics. so, this ret_pan dict should contain per class metrics

Sorry I forget that. Thank you so much for your guidance.
