### ISSUE TITLE
Selection of classes for instance segmentation in structured 3D dataset

### ISSUE THREAD

**Issue by zc-zhao** [filaPro/oneformer3d#98]
Hello authors, thanks for your great efforts. After reading the code, I have one question about the code. In this line of code, [oneformer3d/configs/instance-only-oneformer3d_1xb2_scannet-and-structured3d.py at e2a9dd2656d4b28068](https://github.com/filaPro/oneformer3d/blob/e2a9dd2656d4b2806853c026cab7bc63201f8814/configs/instance-only-oneformer3d_1xb2_scannet-and-structured3d.py#L6) is the selection of the 28 classes official or self-defined? I do not find any evidence to do so.

**Comment by filaPro** [comment]
Unfortunately i also do not remember how these 28 classes was selected out of all 40 classes. Probably, other ones don't have proper instance segmentation annotations... Overall i believe this choice for pre-training classes has minor effect on fine-tuned metrics.
